// !!!GENERATED FILE, DO NOT EDIT!!!
// This file is auto-generated by supabase in scripts/generate-types.ts
// Schema: public
// Generated at: 2025-12-22T07:20:48.909Z

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "13.0.5"
  }
  public: {
    Tables: {
      achievements: {
        Row: {
          achievementId: string
          babyId: string
          category: Database["public"]["Enums"]["achievementCategory"]
          completedDate: string | null
          createdAt: string
          description: string | null
          earned: boolean
          familyId: string
          icon: string
          id: string
          name: string
          progress: number
          rarity: Database["public"]["Enums"]["achievementRarity"]
          target: number
          unlockedAt: string | null
          updatedAt: string | null
          userId: string
        }
        Insert: {
          achievementId: string
          babyId: string
          category: Database["public"]["Enums"]["achievementCategory"]
          completedDate?: string | null
          createdAt?: string
          description?: string | null
          earned?: boolean
          familyId?: string
          icon: string
          id: string
          name: string
          progress?: number
          rarity: Database["public"]["Enums"]["achievementRarity"]
          target: number
          unlockedAt?: string | null
          updatedAt?: string | null
          userId?: string
        }
        Update: {
          achievementId?: string
          babyId?: string
          category?: Database["public"]["Enums"]["achievementCategory"]
          completedDate?: string | null
          createdAt?: string
          description?: string | null
          earned?: boolean
          familyId?: string
          icon?: string
          id?: string
          name?: string
          progress?: number
          rarity?: Database["public"]["Enums"]["achievementRarity"]
          target?: number
          unlockedAt?: string | null
          updatedAt?: string | null
          userId?: string
        }
        Relationships: [
          {
            foreignKeyName: "achievements_babyId_babies_id_fk"
            columns: ["babyId"]
            isOneToOne: false
            referencedRelation: "babies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "achievements_familyId_families_id_fk"
            columns: ["familyId"]
            isOneToOne: false
            referencedRelation: "families"
            referencedColumns: ["id"]
          },
        ]
      }
      activities: {
        Row: {
          amountMl: number | null
          assignedUserId: string | null
          babyId: string | null
          createdAt: string
          details: Json | null
          duration: number | null
          endTime: string | null
          familyId: string
          familyMemberId: string | null
          feedingSource: Database["public"]["Enums"]["feedingSource"] | null
          id: string
          isScheduled: boolean
          notes: string | null
          startTime: string
          subjectType: Database["public"]["Enums"]["activitySubjectType"]
          type: Database["public"]["Enums"]["activityType"]
          updatedAt: string | null
          userId: string
        }
        Insert: {
          amountMl?: number | null
          assignedUserId?: string | null
          babyId?: string | null
          createdAt?: string
          details?: Json | null
          duration?: number | null
          endTime?: string | null
          familyId?: string
          familyMemberId?: string | null
          feedingSource?: Database["public"]["Enums"]["feedingSource"] | null
          id: string
          isScheduled?: boolean
          notes?: string | null
          startTime: string
          subjectType?: Database["public"]["Enums"]["activitySubjectType"]
          type: Database["public"]["Enums"]["activityType"]
          updatedAt?: string | null
          userId?: string
        }
        Update: {
          amountMl?: number | null
          assignedUserId?: string | null
          babyId?: string | null
          createdAt?: string
          details?: Json | null
          duration?: number | null
          endTime?: string | null
          familyId?: string
          familyMemberId?: string | null
          feedingSource?: Database["public"]["Enums"]["feedingSource"] | null
          id?: string
          isScheduled?: boolean
          notes?: string | null
          startTime?: string
          subjectType?: Database["public"]["Enums"]["activitySubjectType"]
          type?: Database["public"]["Enums"]["activityType"]
          updatedAt?: string | null
          userId?: string
        }
        Relationships: [
          {
            foreignKeyName: "activities_assignedUserId_users_id_fk"
            columns: ["assignedUserId"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "activities_babyId_babies_id_fk"
            columns: ["babyId"]
            isOneToOne: false
            referencedRelation: "babies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "activities_familyId_families_id_fk"
            columns: ["familyId"]
            isOneToOne: false
            referencedRelation: "families"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "activities_familyMemberId_familyMembers_id_fk"
            columns: ["familyMemberId"]
            isOneToOne: false
            referencedRelation: "familyMembers"
            referencedColumns: ["id"]
          },
        ]
      }
      babies: {
        Row: {
          avatarBackgroundColor: string | null
          birthDate: string | null
          birthWeightOz: number | null
          createdAt: string
          currentWeightOz: number | null
          customPreferences: Json | null
          dueDate: string | null
          familyId: string
          feedIntervalHours: number | null
          firstName: string
          gender: string | null
          id: string
          journeyStage: Database["public"]["Enums"]["journeyStage"] | null
          lastName: string | null
          metadata: Json | null
          middleName: string | null
          mlPerPump: number | null
          photoUrl: string | null
          pumpsPerDay: number | null
          showActivityTimeline: boolean
          showBathCard: boolean
          showDiaperCard: boolean
          showDoctorVisitCard: boolean
          showFeedingCard: boolean
          showNailTrimmingCard: boolean
          showPumpingCard: boolean
          showSleepCard: boolean
          ttcMethod: Database["public"]["Enums"]["ttcMethod"] | null
          updatedAt: string | null
          userId: string
        }
        Insert: {
          avatarBackgroundColor?: string | null
          birthDate?: string | null
          birthWeightOz?: number | null
          createdAt?: string
          currentWeightOz?: number | null
          customPreferences?: Json | null
          dueDate?: string | null
          familyId?: string
          feedIntervalHours?: number | null
          firstName: string
          gender?: string | null
          id: string
          journeyStage?: Database["public"]["Enums"]["journeyStage"] | null
          lastName?: string | null
          metadata?: Json | null
          middleName?: string | null
          mlPerPump?: number | null
          photoUrl?: string | null
          pumpsPerDay?: number | null
          showActivityTimeline?: boolean
          showBathCard?: boolean
          showDiaperCard?: boolean
          showDoctorVisitCard?: boolean
          showFeedingCard?: boolean
          showNailTrimmingCard?: boolean
          showPumpingCard?: boolean
          showSleepCard?: boolean
          ttcMethod?: Database["public"]["Enums"]["ttcMethod"] | null
          updatedAt?: string | null
          userId?: string
        }
        Update: {
          avatarBackgroundColor?: string | null
          birthDate?: string | null
          birthWeightOz?: number | null
          createdAt?: string
          currentWeightOz?: number | null
          customPreferences?: Json | null
          dueDate?: string | null
          familyId?: string
          feedIntervalHours?: number | null
          firstName?: string
          gender?: string | null
          id?: string
          journeyStage?: Database["public"]["Enums"]["journeyStage"] | null
          lastName?: string | null
          metadata?: Json | null
          middleName?: string | null
          mlPerPump?: number | null
          photoUrl?: string | null
          pumpsPerDay?: number | null
          showActivityTimeline?: boolean
          showBathCard?: boolean
          showDiaperCard?: boolean
          showDoctorVisitCard?: boolean
          showFeedingCard?: boolean
          showNailTrimmingCard?: boolean
          showPumpingCard?: boolean
          showSleepCard?: boolean
          ttcMethod?: Database["public"]["Enums"]["ttcMethod"] | null
          updatedAt?: string | null
          userId?: string
        }
        Relationships: [
          {
            foreignKeyName: "babies_familyId_families_id_fk"
            columns: ["familyId"]
            isOneToOne: false
            referencedRelation: "families"
            referencedColumns: ["id"]
          },
        ]
      }
      celebrationMemories: {
        Row: {
          aiGeneratedAt: string | null
          aiQuestions: Json | null
          aiSummary: string | null
          babyId: string
          celebrationDate: string
          celebrationType: Database["public"]["Enums"]["celebrationType"]
          createdAt: string
          familyId: string
          id: string
          metadata: Json | null
          note: string | null
          photoUrls: Json | null
          sharedWith: Json | null
          updatedAt: string | null
          userId: string
        }
        Insert: {
          aiGeneratedAt?: string | null
          aiQuestions?: Json | null
          aiSummary?: string | null
          babyId: string
          celebrationDate?: string
          celebrationType: Database["public"]["Enums"]["celebrationType"]
          createdAt?: string
          familyId?: string
          id: string
          metadata?: Json | null
          note?: string | null
          photoUrls?: Json | null
          sharedWith?: Json | null
          updatedAt?: string | null
          userId?: string
        }
        Update: {
          aiGeneratedAt?: string | null
          aiQuestions?: Json | null
          aiSummary?: string | null
          babyId?: string
          celebrationDate?: string
          celebrationType?: Database["public"]["Enums"]["celebrationType"]
          createdAt?: string
          familyId?: string
          id?: string
          metadata?: Json | null
          note?: string | null
          photoUrls?: Json | null
          sharedWith?: Json | null
          updatedAt?: string | null
          userId?: string
        }
        Relationships: [
          {
            foreignKeyName: "celebrationMemories_babyId_babies_id_fk"
            columns: ["babyId"]
            isOneToOne: false
            referencedRelation: "babies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "celebrationMemories_familyId_families_id_fk"
            columns: ["familyId"]
            isOneToOne: false
            referencedRelation: "families"
            referencedColumns: ["id"]
          },
        ]
      }
      chatMessages: {
        Row: {
          chatId: string
          content: string
          createdAt: string
          id: string
          role: Database["public"]["Enums"]["messageRole"]
          userId: string | null
        }
        Insert: {
          chatId: string
          content: string
          createdAt?: string
          id: string
          role: Database["public"]["Enums"]["messageRole"]
          userId?: string | null
        }
        Update: {
          chatId?: string
          content?: string
          createdAt?: string
          id?: string
          role?: Database["public"]["Enums"]["messageRole"]
          userId?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "chatMessages_chatId_chats_id_fk"
            columns: ["chatId"]
            isOneToOne: false
            referencedRelation: "chats"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "chatMessages_userId_users_id_fk"
            columns: ["userId"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      chats: {
        Row: {
          babyId: string
          contextId: string | null
          contextType: string | null
          createdAt: string
          familyId: string
          id: string
          summary: string | null
          title: string
          updatedAt: string | null
          userId: string
        }
        Insert: {
          babyId: string
          contextId?: string | null
          contextType?: string | null
          createdAt?: string
          familyId?: string
          id: string
          summary?: string | null
          title?: string
          updatedAt?: string | null
          userId?: string
        }
        Update: {
          babyId?: string
          contextId?: string | null
          contextType?: string | null
          createdAt?: string
          familyId?: string
          id?: string
          summary?: string | null
          title?: string
          updatedAt?: string | null
          userId?: string
        }
        Relationships: [
          {
            foreignKeyName: "chats_babyId_babies_id_fk"
            columns: ["babyId"]
            isOneToOne: false
            referencedRelation: "babies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "chats_familyId_families_id_fk"
            columns: ["familyId"]
            isOneToOne: false
            referencedRelation: "families"
            referencedColumns: ["id"]
          },
        ]
      }
      contentCache: {
        Row: {
          babyId: string
          createdAt: string
          expiresAt: string
          familyId: string
          id: string
          key: string
          updatedAt: string | null
          userId: string
          value: Json
        }
        Insert: {
          babyId: string
          createdAt?: string
          expiresAt: string
          familyId?: string
          id: string
          key: string
          updatedAt?: string | null
          userId?: string
          value: Json
        }
        Update: {
          babyId?: string
          createdAt?: string
          expiresAt?: string
          familyId?: string
          id?: string
          key?: string
          updatedAt?: string | null
          userId?: string
          value?: Json
        }
        Relationships: [
          {
            foreignKeyName: "contentCache_babyId_babies_id_fk"
            columns: ["babyId"]
            isOneToOne: false
            referencedRelation: "babies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "contentCache_familyId_families_id_fk"
            columns: ["familyId"]
            isOneToOne: false
            referencedRelation: "families"
            referencedColumns: ["id"]
          },
        ]
      }
      developmentalPhaseProgress: {
        Row: {
          babyId: string
          checklistItems: Json
          completedAt: string | null
          createdAt: string
          familyId: string
          id: string
          phaseId: string
          subPhaseType: Database["public"]["Enums"]["developmentalSubPhaseType"]
          updatedAt: string | null
          userId: string
        }
        Insert: {
          babyId: string
          checklistItems?: Json
          completedAt?: string | null
          createdAt?: string
          familyId?: string
          id: string
          phaseId: string
          subPhaseType: Database["public"]["Enums"]["developmentalSubPhaseType"]
          updatedAt?: string | null
          userId?: string
        }
        Update: {
          babyId?: string
          checklistItems?: Json
          completedAt?: string | null
          createdAt?: string
          familyId?: string
          id?: string
          phaseId?: string
          subPhaseType?: Database["public"]["Enums"]["developmentalSubPhaseType"]
          updatedAt?: string | null
          userId?: string
        }
        Relationships: [
          {
            foreignKeyName: "developmentalPhaseProgress_babyId_babies_id_fk"
            columns: ["babyId"]
            isOneToOne: false
            referencedRelation: "babies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "developmentalPhaseProgress_familyId_families_id_fk"
            columns: ["familyId"]
            isOneToOne: false
            referencedRelation: "families"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "developmentalPhaseProgress_phaseId_developmentalPhases_id_fk"
            columns: ["phaseId"]
            isOneToOne: false
            referencedRelation: "developmentalPhases"
            referencedColumns: ["id"]
          },
        ]
      }
      developmentalPhases: {
        Row: {
          createdAt: string
          description: string | null
          endDay: number
          id: string
          name: string
          phaseNumber: number
          startDay: number
          updatedAt: string | null
        }
        Insert: {
          createdAt?: string
          description?: string | null
          endDay: number
          id: string
          name: string
          phaseNumber: number
          startDay: number
          updatedAt?: string | null
        }
        Update: {
          createdAt?: string
          description?: string | null
          endDay?: number
          id?: string
          name?: string
          phaseNumber?: number
          startDay?: number
          updatedAt?: string | null
        }
        Relationships: []
      }
      families: {
        Row: {
          clerkOrgId: string
          createdAt: string | null
          createdByUserId: string
          id: string
          name: string
          stripeCustomerId: string | null
          stripeSubscriptionId: string | null
          stripeSubscriptionStatus:
            | Database["public"]["Enums"]["stripeSubscriptionStatus"]
            | null
          updatedAt: string | null
        }
        Insert: {
          clerkOrgId: string
          createdAt?: string | null
          createdByUserId: string
          id: string
          name: string
          stripeCustomerId?: string | null
          stripeSubscriptionId?: string | null
          stripeSubscriptionStatus?:
            | Database["public"]["Enums"]["stripeSubscriptionStatus"]
            | null
          updatedAt?: string | null
        }
        Update: {
          clerkOrgId?: string
          createdAt?: string | null
          createdByUserId?: string
          id?: string
          name?: string
          stripeCustomerId?: string | null
          stripeSubscriptionId?: string | null
          stripeSubscriptionStatus?:
            | Database["public"]["Enums"]["stripeSubscriptionStatus"]
            | null
          updatedAt?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "families_createdByUserId_users_id_fk"
            columns: ["createdByUserId"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      familyMembers: {
        Row: {
          createdAt: string | null
          familyId: string
          id: string
          onboardingCompletedAt: string | null
          role: Database["public"]["Enums"]["userRole"]
          updatedAt: string | null
          userId: string
          userRole: Database["public"]["Enums"]["userRole"] | null
        }
        Insert: {
          createdAt?: string | null
          familyId?: string
          id: string
          onboardingCompletedAt?: string | null
          role?: Database["public"]["Enums"]["userRole"]
          updatedAt?: string | null
          userId?: string
          userRole?: Database["public"]["Enums"]["userRole"] | null
        }
        Update: {
          createdAt?: string | null
          familyId?: string
          id?: string
          onboardingCompletedAt?: string | null
          role?: Database["public"]["Enums"]["userRole"]
          updatedAt?: string | null
          userId?: string
          userRole?: Database["public"]["Enums"]["userRole"] | null
        }
        Relationships: [
          {
            foreignKeyName: "familyMembers_familyId_families_id_fk"
            columns: ["familyId"]
            isOneToOne: false
            referencedRelation: "families"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "familyMembers_userId_users_id_fk"
            columns: ["userId"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      growthRecords: {
        Row: {
          babyId: string
          createdAt: string
          date: string
          familyId: string
          headCircumference: number | null
          height: number | null
          id: string
          metadata: Json | null
          notes: string | null
          updatedAt: string | null
          userId: string
          weight: number | null
        }
        Insert: {
          babyId: string
          createdAt?: string
          date: string
          familyId?: string
          headCircumference?: number | null
          height?: number | null
          id: string
          metadata?: Json | null
          notes?: string | null
          updatedAt?: string | null
          userId?: string
          weight?: number | null
        }
        Update: {
          babyId?: string
          createdAt?: string
          date?: string
          familyId?: string
          headCircumference?: number | null
          height?: number | null
          id?: string
          metadata?: Json | null
          notes?: string | null
          updatedAt?: string | null
          userId?: string
          weight?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "growthRecords_babyId_babies_id_fk"
            columns: ["babyId"]
            isOneToOne: false
            referencedRelation: "babies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "growthRecords_familyId_families_id_fk"
            columns: ["familyId"]
            isOneToOne: false
            referencedRelation: "families"
            referencedColumns: ["id"]
          },
        ]
      }
      invitations: {
        Row: {
          code: string
          createdAt: string | null
          expiresAt: string
          familyId: string
          id: string
          invitedByUserId: string
          isActive: boolean
          role: Database["public"]["Enums"]["userRole"]
          updatedAt: string | null
          usedAt: string | null
          usedByUserId: string | null
        }
        Insert: {
          code: string
          createdAt?: string | null
          expiresAt: string
          familyId?: string
          id: string
          invitedByUserId?: string
          isActive?: boolean
          role?: Database["public"]["Enums"]["userRole"]
          updatedAt?: string | null
          usedAt?: string | null
          usedByUserId?: string | null
        }
        Update: {
          code?: string
          createdAt?: string | null
          expiresAt?: string
          familyId?: string
          id?: string
          invitedByUserId?: string
          isActive?: boolean
          role?: Database["public"]["Enums"]["userRole"]
          updatedAt?: string | null
          usedAt?: string | null
          usedByUserId?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "invitations_familyId_families_id_fk"
            columns: ["familyId"]
            isOneToOne: false
            referencedRelation: "families"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "invitations_invitedByUserId_users_id_fk"
            columns: ["invitedByUserId"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "invitations_usedByUserId_users_id_fk"
            columns: ["usedByUserId"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      medicalRecords: {
        Row: {
          activityId: string | null
          babyId: string
          createdAt: string
          date: string
          description: string | null
          doctorName: string | null
          familyId: string
          headCircumferenceCm: number | null
          id: string
          lengthCm: number | null
          location: string | null
          metadata: Json | null
          provider: string | null
          title: string
          type: string
          updatedAt: string | null
          userId: string
          vaccinations: Json | null
          visitType: string | null
          weightKg: number | null
        }
        Insert: {
          activityId?: string | null
          babyId: string
          createdAt?: string
          date: string
          description?: string | null
          doctorName?: string | null
          familyId?: string
          headCircumferenceCm?: number | null
          id: string
          lengthCm?: number | null
          location?: string | null
          metadata?: Json | null
          provider?: string | null
          title: string
          type: string
          updatedAt?: string | null
          userId?: string
          vaccinations?: Json | null
          visitType?: string | null
          weightKg?: number | null
        }
        Update: {
          activityId?: string | null
          babyId?: string
          createdAt?: string
          date?: string
          description?: string | null
          doctorName?: string | null
          familyId?: string
          headCircumferenceCm?: number | null
          id?: string
          lengthCm?: number | null
          location?: string | null
          metadata?: Json | null
          provider?: string | null
          title?: string
          type?: string
          updatedAt?: string | null
          userId?: string
          vaccinations?: Json | null
          visitType?: string | null
          weightKg?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "medicalRecords_activityId_activities_id_fk"
            columns: ["activityId"]
            isOneToOne: false
            referencedRelation: "activities"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "medicalRecords_babyId_babies_id_fk"
            columns: ["babyId"]
            isOneToOne: false
            referencedRelation: "babies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "medicalRecords_familyId_families_id_fk"
            columns: ["familyId"]
            isOneToOne: false
            referencedRelation: "families"
            referencedColumns: ["id"]
          },
        ]
      }
      milestoneQuestionResponses: {
        Row: {
          answer: Database["public"]["Enums"]["questionAnswer"]
          babyId: string
          chatId: string | null
          contextId: string
          contextType: string
          createdAt: string
          familyId: string
          id: string
          question: string
          updatedAt: string | null
          userId: string
        }
        Insert: {
          answer: Database["public"]["Enums"]["questionAnswer"]
          babyId: string
          chatId?: string | null
          contextId: string
          contextType: string
          createdAt?: string
          familyId?: string
          id: string
          question: string
          updatedAt?: string | null
          userId?: string
        }
        Update: {
          answer?: Database["public"]["Enums"]["questionAnswer"]
          babyId?: string
          chatId?: string | null
          contextId?: string
          contextType?: string
          createdAt?: string
          familyId?: string
          id?: string
          question?: string
          updatedAt?: string | null
          userId?: string
        }
        Relationships: [
          {
            foreignKeyName: "milestoneQuestionResponses_babyId_babies_id_fk"
            columns: ["babyId"]
            isOneToOne: false
            referencedRelation: "babies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "milestoneQuestionResponses_chatId_chats_id_fk"
            columns: ["chatId"]
            isOneToOne: false
            referencedRelation: "chats"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "milestoneQuestionResponses_familyId_families_id_fk"
            columns: ["familyId"]
            isOneToOne: false
            referencedRelation: "families"
            referencedColumns: ["id"]
          },
        ]
      }
      milestones: {
        Row: {
          achievedDate: string | null
          babyId: string
          createdAt: string
          description: string | null
          familyId: string
          id: string
          isSuggested: boolean
          metadata: Json | null
          photoUrl: string | null
          suggestedDay: number | null
          title: string
          type: Database["public"]["Enums"]["milestoneType"]
          updatedAt: string | null
          userId: string
        }
        Insert: {
          achievedDate?: string | null
          babyId: string
          createdAt?: string
          description?: string | null
          familyId?: string
          id: string
          isSuggested?: boolean
          metadata?: Json | null
          photoUrl?: string | null
          suggestedDay?: number | null
          title: string
          type: Database["public"]["Enums"]["milestoneType"]
          updatedAt?: string | null
          userId?: string
        }
        Update: {
          achievedDate?: string | null
          babyId?: string
          createdAt?: string
          description?: string | null
          familyId?: string
          id?: string
          isSuggested?: boolean
          metadata?: Json | null
          photoUrl?: string | null
          suggestedDay?: number | null
          title?: string
          type?: Database["public"]["Enums"]["milestoneType"]
          updatedAt?: string | null
          userId?: string
        }
        Relationships: [
          {
            foreignKeyName: "milestones_babyId_babies_id_fk"
            columns: ["babyId"]
            isOneToOne: false
            referencedRelation: "babies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "milestones_familyId_families_id_fk"
            columns: ["familyId"]
            isOneToOne: false
            referencedRelation: "families"
            referencedColumns: ["id"]
          },
        ]
      }
      parentCheckIns: {
        Row: {
          aiGeneratedQuestions: boolean | null
          concernsRaised: Json | null
          createdAt: string
          date: string
          familyId: string
          id: string
          moodScore: number | null
          questionContext: Json | null
          responses: Json
          updatedAt: string | null
          userId: string
        }
        Insert: {
          aiGeneratedQuestions?: boolean | null
          concernsRaised?: Json | null
          createdAt?: string
          date?: string
          familyId?: string
          id: string
          moodScore?: number | null
          questionContext?: Json | null
          responses: Json
          updatedAt?: string | null
          userId: string
        }
        Update: {
          aiGeneratedQuestions?: boolean | null
          concernsRaised?: Json | null
          createdAt?: string
          date?: string
          familyId?: string
          id?: string
          moodScore?: number | null
          questionContext?: Json | null
          responses?: Json
          updatedAt?: string | null
          userId?: string
        }
        Relationships: [
          {
            foreignKeyName: "parentCheckIns_familyId_families_id_fk"
            columns: ["familyId"]
            isOneToOne: false
            referencedRelation: "families"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "parentCheckIns_userId_users_id_fk"
            columns: ["userId"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      parentDailyResponses: {
        Row: {
          answerChoices: Json
          babyId: string
          createdAt: string
          date: string
          familyId: string
          id: string
          question: string
          questionContext: Json | null
          selectedAnswer: string | null
          updatedAt: string | null
          userId: string
        }
        Insert: {
          answerChoices: Json
          babyId: string
          createdAt?: string
          date?: string
          familyId?: string
          id: string
          question: string
          questionContext?: Json | null
          selectedAnswer?: string | null
          updatedAt?: string | null
          userId: string
        }
        Update: {
          answerChoices?: Json
          babyId?: string
          createdAt?: string
          date?: string
          familyId?: string
          id?: string
          question?: string
          questionContext?: Json | null
          selectedAnswer?: string | null
          updatedAt?: string | null
          userId?: string
        }
        Relationships: [
          {
            foreignKeyName: "parentDailyResponses_babyId_babies_id_fk"
            columns: ["babyId"]
            isOneToOne: false
            referencedRelation: "babies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "parentDailyResponses_familyId_families_id_fk"
            columns: ["familyId"]
            isOneToOne: false
            referencedRelation: "families"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "parentDailyResponses_userId_users_id_fk"
            columns: ["userId"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      parentTasks: {
        Row: {
          category: Database["public"]["Enums"]["taskCategory"]
          completed: boolean
          completedAt: string | null
          context: Json | null
          createdAt: string
          estimatedMinutes: number | null
          familyId: string
          generatedDate: string
          id: string
          priority: Database["public"]["Enums"]["taskPriority"]
          suggestedTime: string | null
          taskText: string
          updatedAt: string | null
          userId: string
          whyItMatters: string | null
        }
        Insert: {
          category: Database["public"]["Enums"]["taskCategory"]
          completed?: boolean
          completedAt?: string | null
          context?: Json | null
          createdAt?: string
          estimatedMinutes?: number | null
          familyId?: string
          generatedDate?: string
          id: string
          priority?: Database["public"]["Enums"]["taskPriority"]
          suggestedTime?: string | null
          taskText: string
          updatedAt?: string | null
          userId: string
          whyItMatters?: string | null
        }
        Update: {
          category?: Database["public"]["Enums"]["taskCategory"]
          completed?: boolean
          completedAt?: string | null
          context?: Json | null
          createdAt?: string
          estimatedMinutes?: number | null
          familyId?: string
          generatedDate?: string
          id?: string
          priority?: Database["public"]["Enums"]["taskPriority"]
          suggestedTime?: string | null
          taskText?: string
          updatedAt?: string | null
          userId?: string
          whyItMatters?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "parentTasks_familyId_families_id_fk"
            columns: ["familyId"]
            isOneToOne: false
            referencedRelation: "families"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "parentTasks_userId_users_id_fk"
            columns: ["userId"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      pushSubscriptions: {
        Row: {
          auth: string
          createdAt: string | null
          endpoint: string
          id: string
          p256dh: string
          updatedAt: string | null
          userId: string
        }
        Insert: {
          auth: string
          createdAt?: string | null
          endpoint: string
          id: string
          p256dh: string
          updatedAt?: string | null
          userId?: string
        }
        Update: {
          auth?: string
          createdAt?: string | null
          endpoint?: string
          id?: string
          p256dh?: string
          updatedAt?: string | null
          userId?: string
        }
        Relationships: [
          {
            foreignKeyName: "pushSubscriptions_userId_users_id_fk"
            columns: ["userId"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      shortUrls: {
        Row: {
          code: string
          createdAt: string | null
          expiresAt: string | null
          familyId: string
          id: string
          isActive: boolean
          redirectUrl: string
          updatedAt: string | null
          userId: string
        }
        Insert: {
          code: string
          createdAt?: string | null
          expiresAt?: string | null
          familyId?: string
          id: string
          isActive?: boolean
          redirectUrl: string
          updatedAt?: string | null
          userId?: string
        }
        Update: {
          code?: string
          createdAt?: string | null
          expiresAt?: string | null
          familyId?: string
          id?: string
          isActive?: boolean
          redirectUrl?: string
          updatedAt?: string | null
          userId?: string
        }
        Relationships: [
          {
            foreignKeyName: "shortUrls_familyId_families_id_fk"
            columns: ["familyId"]
            isOneToOne: false
            referencedRelation: "families"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "shortUrls_userId_users_id_fk"
            columns: ["userId"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      supplyInventory: {
        Row: {
          babyId: string
          createdAt: string
          donorMl: number
          familyId: string
          formulaMl: number
          id: string
          pumpedMl: number
          updatedAt: string | null
          userId: string
        }
        Insert: {
          babyId: string
          createdAt?: string
          donorMl?: number
          familyId?: string
          formulaMl?: number
          id: string
          pumpedMl?: number
          updatedAt?: string | null
          userId?: string
        }
        Update: {
          babyId?: string
          createdAt?: string
          donorMl?: number
          familyId?: string
          formulaMl?: number
          id?: string
          pumpedMl?: number
          updatedAt?: string | null
          userId?: string
        }
        Relationships: [
          {
            foreignKeyName: "supplyInventory_babyId_babies_id_fk"
            columns: ["babyId"]
            isOneToOne: false
            referencedRelation: "babies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "supplyInventory_familyId_families_id_fk"
            columns: ["familyId"]
            isOneToOne: false
            referencedRelation: "families"
            referencedColumns: ["id"]
          },
        ]
      }
      supplyTransactions: {
        Row: {
          amountMl: number
          babyId: string
          createdAt: string
          familyId: string
          id: string
          notes: string | null
          source: Database["public"]["Enums"]["feedingSource"]
          timestamp: string
          type: Database["public"]["Enums"]["supplyTransactionType"]
          updatedAt: string | null
          userId: string
        }
        Insert: {
          amountMl: number
          babyId: string
          createdAt?: string
          familyId?: string
          id: string
          notes?: string | null
          source: Database["public"]["Enums"]["feedingSource"]
          timestamp?: string
          type: Database["public"]["Enums"]["supplyTransactionType"]
          updatedAt?: string | null
          userId?: string
        }
        Update: {
          amountMl?: number
          babyId?: string
          createdAt?: string
          familyId?: string
          id?: string
          notes?: string | null
          source?: Database["public"]["Enums"]["feedingSource"]
          timestamp?: string
          type?: Database["public"]["Enums"]["supplyTransactionType"]
          updatedAt?: string | null
          userId?: string
        }
        Relationships: [
          {
            foreignKeyName: "supplyTransactions_babyId_babies_id_fk"
            columns: ["babyId"]
            isOneToOne: false
            referencedRelation: "babies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "supplyTransactions_familyId_families_id_fk"
            columns: ["familyId"]
            isOneToOne: false
            referencedRelation: "families"
            referencedColumns: ["id"]
          },
        ]
      }
      users: {
        Row: {
          alarmDiaperEnabled: boolean
          alarmDiaperThreshold: number | null
          alarmFeedingEnabled: boolean
          alarmFeedingThreshold: number | null
          alarmPumpingEnabled: boolean
          alarmPumpingThreshold: number | null
          alarmSleepEnabled: boolean
          alarmSleepThreshold: number | null
          avatarUrl: string | null
          clerkId: string
          createdAt: string
          defaultHomeScreenId: string | null
          defaultHomeScreenType: string | null
          email: string
          firstName: string | null
          hasSeenParentWellnessIntro: boolean
          id: string
          lastLoggedInAt: string | null
          lastName: string | null
          lastSelectedBabyId: string | null
          lastSelectedFamilyId: string | null
          measurementUnit: Database["public"]["Enums"]["measurementUnit"]
          online: boolean
          quickLogDiaperUsePredictedType: boolean
          quickLogEnabled: boolean
          quickLogFeedingUseLastAmount: boolean
          quickLogFeedingUseLastType: boolean
          quickLogFeedingUseTypicalDuration: boolean
          quickLogPumpingUseLastVolume: boolean
          quickLogPumpingUseTypicalDuration: boolean
          quickLogSleepUseSuggestedDuration: boolean
          showActivityGoals: boolean
          showParentWellnessCard: boolean
          showPredictiveTimes: boolean
          temperatureUnit: Database["public"]["Enums"]["temperatureUnit"]
          theme: Database["public"]["Enums"]["theme"]
          timeFormat: Database["public"]["Enums"]["timeFormat"]
          updatedAt: string | null
          weekStartDay: number | null
        }
        Insert: {
          alarmDiaperEnabled?: boolean
          alarmDiaperThreshold?: number | null
          alarmFeedingEnabled?: boolean
          alarmFeedingThreshold?: number | null
          alarmPumpingEnabled?: boolean
          alarmPumpingThreshold?: number | null
          alarmSleepEnabled?: boolean
          alarmSleepThreshold?: number | null
          avatarUrl?: string | null
          clerkId: string
          createdAt?: string
          defaultHomeScreenId?: string | null
          defaultHomeScreenType?: string | null
          email: string
          firstName?: string | null
          hasSeenParentWellnessIntro?: boolean
          id: string
          lastLoggedInAt?: string | null
          lastName?: string | null
          lastSelectedBabyId?: string | null
          lastSelectedFamilyId?: string | null
          measurementUnit?: Database["public"]["Enums"]["measurementUnit"]
          online?: boolean
          quickLogDiaperUsePredictedType?: boolean
          quickLogEnabled?: boolean
          quickLogFeedingUseLastAmount?: boolean
          quickLogFeedingUseLastType?: boolean
          quickLogFeedingUseTypicalDuration?: boolean
          quickLogPumpingUseLastVolume?: boolean
          quickLogPumpingUseTypicalDuration?: boolean
          quickLogSleepUseSuggestedDuration?: boolean
          showActivityGoals?: boolean
          showParentWellnessCard?: boolean
          showPredictiveTimes?: boolean
          temperatureUnit?: Database["public"]["Enums"]["temperatureUnit"]
          theme?: Database["public"]["Enums"]["theme"]
          timeFormat?: Database["public"]["Enums"]["timeFormat"]
          updatedAt?: string | null
          weekStartDay?: number | null
        }
        Update: {
          alarmDiaperEnabled?: boolean
          alarmDiaperThreshold?: number | null
          alarmFeedingEnabled?: boolean
          alarmFeedingThreshold?: number | null
          alarmPumpingEnabled?: boolean
          alarmPumpingThreshold?: number | null
          alarmSleepEnabled?: boolean
          alarmSleepThreshold?: number | null
          avatarUrl?: string | null
          clerkId?: string
          createdAt?: string
          defaultHomeScreenId?: string | null
          defaultHomeScreenType?: string | null
          email?: string
          firstName?: string | null
          hasSeenParentWellnessIntro?: boolean
          id?: string
          lastLoggedInAt?: string | null
          lastName?: string | null
          lastSelectedBabyId?: string | null
          lastSelectedFamilyId?: string | null
          measurementUnit?: Database["public"]["Enums"]["measurementUnit"]
          online?: boolean
          quickLogDiaperUsePredictedType?: boolean
          quickLogEnabled?: boolean
          quickLogFeedingUseLastAmount?: boolean
          quickLogFeedingUseLastType?: boolean
          quickLogFeedingUseTypicalDuration?: boolean
          quickLogPumpingUseLastVolume?: boolean
          quickLogPumpingUseTypicalDuration?: boolean
          quickLogSleepUseSuggestedDuration?: boolean
          showActivityGoals?: boolean
          showParentWellnessCard?: boolean
          showPredictiveTimes?: boolean
          temperatureUnit?: Database["public"]["Enums"]["temperatureUnit"]
          theme?: Database["public"]["Enums"]["theme"]
          timeFormat?: Database["public"]["Enums"]["timeFormat"]
          updatedAt?: string | null
          weekStartDay?: number | null
        }
        Relationships: []
      }
      wellnessAssessments: {
        Row: {
          assessmentType: string
          createdAt: string
          date: string
          familyId: string
          followUpScheduled: string | null
          id: string
          notes: string | null
          questions: Json
          recommendations: Json | null
          responses: Json
          riskScore: number | null
          updatedAt: string | null
          userId: string
        }
        Insert: {
          assessmentType: string
          createdAt?: string
          date?: string
          familyId?: string
          followUpScheduled?: string | null
          id: string
          notes?: string | null
          questions: Json
          recommendations?: Json | null
          responses: Json
          riskScore?: number | null
          updatedAt?: string | null
          userId: string
        }
        Update: {
          assessmentType?: string
          createdAt?: string
          date?: string
          familyId?: string
          followUpScheduled?: string | null
          id?: string
          notes?: string | null
          questions?: Json
          recommendations?: Json | null
          responses?: Json
          riskScore?: number | null
          updatedAt?: string | null
          userId?: string
        }
        Relationships: [
          {
            foreignKeyName: "wellnessAssessments_familyId_families_id_fk"
            columns: ["familyId"]
            isOneToOne: false
            referencedRelation: "families"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "wellnessAssessments_userId_users_id_fk"
            columns: ["userId"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      requesting_family_id: { Args: never; Returns: string }
      requesting_user_id: { Args: never; Returns: string }
    }
    Enums: {
      achievementCategory:
        | "foundation"
        | "volume"
        | "streaks"
        | "activity-specific"
        | "efficiency"
        | "records"
        | "time-based"
        | "special"
        | "personal-milestones"
        | "parent-milestones"
        | "daily-achievements"
      achievementRarity: "common" | "rare" | "epic" | "legendary"
      activitySubjectType: "baby" | "family_member"
      activityType:
        | "sleep"
        | "feeding"
        | "bottle"
        | "nursing"
        | "pumping"
        | "diaper"
        | "wet"
        | "dirty"
        | "both"
        | "solids"
        | "bath"
        | "medicine"
        | "temperature"
        | "tummy_time"
        | "growth"
        | "potty"
        | "doctor_visit"
        | "vitamin_d"
        | "nail_trimming"
        | "stroller_walk"
        | "contrast_time"
      celebrationType:
        | "week_1"
        | "week_2"
        | "week_3"
        | "week_4"
        | "week_5"
        | "week_6"
        | "week_7"
        | "week_8"
        | "week_9"
        | "week_10"
        | "week_11"
        | "week_12"
        | "month_1"
        | "month_2"
        | "month_3"
        | "month_4"
        | "month_5"
        | "month_6"
        | "month_9"
        | "year_1"
        | "month_18"
        | "year_2"
      checkInCategory:
        | "physical"
        | "emotional"
        | "support"
        | "baby_concern"
        | "self_care"
      checkInResponseType:
        | "emoji_scale"
        | "yes_no"
        | "rating_1_5"
        | "text_short"
      developmentalSubPhaseType: "fussy" | "skills"
      diaperColor:
        | "yellow"
        | "brown"
        | "green"
        | "black"
        | "red"
        | "white"
        | "orange"
      diaperConsistency:
        | "solid"
        | "loose"
        | "runny"
        | "mucousy"
        | "hard"
        | "pebbles"
        | "diarrhea"
      diaperSize: "little" | "medium" | "large"
      feedingSource: "pumped" | "donor" | "direct" | "formula"
      journeyStage: "ttc" | "pregnant" | "born"
      localConnectionStatus: "connected" | "disconnected"
      measurementUnit: "imperial" | "metric"
      messageRole: "user" | "assistant"
      milestoneType:
        | "physical"
        | "cognitive"
        | "social"
        | "language"
        | "self_care"
      questionAnswer: "yes" | "no"
      sleepLocation:
        | "crib"
        | "bassinet"
        | "bed"
        | "car_seat"
        | "stroller"
        | "arms"
        | "swing"
        | "bouncer"
      sleepQuality: "peaceful" | "restless" | "fussy" | "crying"
      stripeSubscriptionStatus:
        | "active"
        | "canceled"
        | "incomplete"
        | "incomplete_expired"
        | "past_due"
        | "paused"
        | "trialing"
        | "unpaid"
      supplyTransactionType: "add" | "deduct"
      taskCategory:
        | "baby_care"
        | "household"
        | "self_care"
        | "relationship"
        | "preparation"
      taskPriority: "high" | "medium" | "low"
      temperatureUnit: "fahrenheit" | "celsius"
      theme: "light" | "dark" | "system"
      timeFormat: "12h" | "24h"
      ttcMethod: "natural" | "ivf" | "other"
      userRole: "primary" | "partner" | "caregiver"
      wakeReason:
        | "hungry"
        | "diaper"
        | "crying"
        | "naturally"
        | "noise"
        | "unknown"
      wellnessQuestionCategory:
        | "mood"
        | "anxiety"
        | "bonding"
        | "coping"
        | "thoughts"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      achievementCategory: [
        "foundation",
        "volume",
        "streaks",
        "activity-specific",
        "efficiency",
        "records",
        "time-based",
        "special",
        "personal-milestones",
        "parent-milestones",
        "daily-achievements",
      ],
      achievementRarity: ["common", "rare", "epic", "legendary"],
      activitySubjectType: ["baby", "family_member"],
      activityType: [
        "sleep",
        "feeding",
        "bottle",
        "nursing",
        "pumping",
        "diaper",
        "wet",
        "dirty",
        "both",
        "solids",
        "bath",
        "medicine",
        "temperature",
        "tummy_time",
        "growth",
        "potty",
        "doctor_visit",
        "vitamin_d",
        "nail_trimming",
        "stroller_walk",
        "contrast_time",
      ],
      celebrationType: [
        "week_1",
        "week_2",
        "week_3",
        "week_4",
        "week_5",
        "week_6",
        "week_7",
        "week_8",
        "week_9",
        "week_10",
        "week_11",
        "week_12",
        "month_1",
        "month_2",
        "month_3",
        "month_4",
        "month_5",
        "month_6",
        "month_9",
        "year_1",
        "month_18",
        "year_2",
      ],
      checkInCategory: [
        "physical",
        "emotional",
        "support",
        "baby_concern",
        "self_care",
      ],
      checkInResponseType: [
        "emoji_scale",
        "yes_no",
        "rating_1_5",
        "text_short",
      ],
      developmentalSubPhaseType: ["fussy", "skills"],
      diaperColor: [
        "yellow",
        "brown",
        "green",
        "black",
        "red",
        "white",
        "orange",
      ],
      diaperConsistency: [
        "solid",
        "loose",
        "runny",
        "mucousy",
        "hard",
        "pebbles",
        "diarrhea",
      ],
      diaperSize: ["little", "medium", "large"],
      feedingSource: ["pumped", "donor", "direct", "formula"],
      journeyStage: ["ttc", "pregnant", "born"],
      localConnectionStatus: ["connected", "disconnected"],
      measurementUnit: ["imperial", "metric"],
      messageRole: ["user", "assistant"],
      milestoneType: [
        "physical",
        "cognitive",
        "social",
        "language",
        "self_care",
      ],
      questionAnswer: ["yes", "no"],
      sleepLocation: [
        "crib",
        "bassinet",
        "bed",
        "car_seat",
        "stroller",
        "arms",
        "swing",
        "bouncer",
      ],
      sleepQuality: ["peaceful", "restless", "fussy", "crying"],
      stripeSubscriptionStatus: [
        "active",
        "canceled",
        "incomplete",
        "incomplete_expired",
        "past_due",
        "paused",
        "trialing",
        "unpaid",
      ],
      supplyTransactionType: ["add", "deduct"],
      taskCategory: [
        "baby_care",
        "household",
        "self_care",
        "relationship",
        "preparation",
      ],
      taskPriority: ["high", "medium", "low"],
      temperatureUnit: ["fahrenheit", "celsius"],
      theme: ["light", "dark", "system"],
      timeFormat: ["12h", "24h"],
      ttcMethod: ["natural", "ivf", "other"],
      userRole: ["primary", "partner", "caregiver"],
      wakeReason: [
        "hungry",
        "diaper",
        "crying",
        "naturally",
        "noise",
        "unknown",
      ],
      wellnessQuestionCategory: [
        "mood",
        "anxiety",
        "bonding",
        "coping",
        "thoughts",
      ],
    },
  },
} as const
